# Intrduction to NumPy


#### 1. Import NumPy under the name np.

In [100]:
# your code here
import numpy as np

#### 2. Print your NumPy version.

In [101]:
# your code here
np.version.version

'1.19.2'

#### 3. Generate a 2x3x5 3-dimensional array with random values. Assign the array to variable *a*.
**Challenge**: there are at least three easy ways that use numpy to generate random arrays. How many ways can you find?

In [130]:
# Method 1
a = np.random.random([2,3,5])

In [110]:
# Method 2
a = np.random.randint(100,size=[2,3,5])

[[[82 62  0 93 67]
  [ 1  6  5 88 48]
  [14 91 94 98 87]]

 [[20 31 23 18 55]
  [21  0 87 28 82]
  [ 8 64 69 94 20]]]


In [129]:
# Method 3
sample = [i for i in range(100)]
a = np.random.choice(sample,size=[2,3,5])

#### 4. Print *a*.


In [112]:
# your code here
print(a)

[[[82 62  0 93 67]
  [ 1  6  5 88 48]
  [14 91 94 98 87]]

 [[20 31 23 18 55]
  [21  0 87 28 82]
  [ 8 64 69 94 20]]]


#### 5. Create a 5x2x3 3-dimensional array with all values equaling 1. Assign the array to variable *b*.

In [113]:
# your code here
b = np.ones([5,2,3])

#### 6. Print *b*.


In [114]:
# your code here
print(b)

[[[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]]]


#### 7. Do *a* and *b* have the same size? How do you prove that in Python code?

In [115]:
# your code here
if a.size == b.size:
    print(True)
else:
    print(False)

True


#### 8. Are you able to add *a* and *b*? Why or why not?


In [116]:
# your answer here
a+b
#because the size is the same, but the shape is different

ValueError: operands could not be broadcast together with shapes (2,3,5) (5,2,3) 

#### 9. Transpose *b* so that it has the same structure of *a* (i.e. become a 2x3x5 array). Assign the transposed array to variable *c*.

In [117]:
# your code here
c = b.transpose(1,2,0)
print(c.shape)

(2, 3, 5)


#### 10. Try to add *a* and *c*. Now it should work. Assign the sum to variable *d*. But why does it work now?

In [118]:
# your code/answer here
d = a+c

#### 11. Print *a* and *d*. Notice the difference and relation of the two array in terms of the values? Explain.

In [119]:
# your code/answer here
print(a)
print(d)
#we added 1 to all a's elements in the previous operation

[[[82 62  0 93 67]
  [ 1  6  5 88 48]
  [14 91 94 98 87]]

 [[20 31 23 18 55]
  [21  0 87 28 82]
  [ 8 64 69 94 20]]]
[[[83. 63.  1. 94. 68.]
  [ 2.  7.  6. 89. 49.]
  [15. 92. 95. 99. 88.]]

 [[21. 32. 24. 19. 56.]
  [22.  1. 88. 29. 83.]
  [ 9. 65. 70. 95. 21.]]]


#### 12. Multiply *a* and *c*. Assign the result to *e*.

In [120]:
# your code here
e = np.multiply(a,c)
print(e)

[[[82. 62.  0. 93. 67.]
  [ 1.  6.  5. 88. 48.]
  [14. 91. 94. 98. 87.]]

 [[20. 31. 23. 18. 55.]
  [21.  0. 87. 28. 82.]
  [ 8. 64. 69. 94. 20.]]]


#### 13. Does *e* equal to *a*? Why or why not?


In [121]:
# your code/answer here
if e.all() == a.all():
    print(True)
else:
    print(False)
#it is because we multiplied array a by a unitiry matrix

True


#### 14. Identify the max, min, and mean values in *d*. Assign those values to variables *d_max*, *d_min* and *d_mean*.

In [122]:
# your code here
d_max = d.max()
d_min = d.min()
d_mean = d.mean()

#### 15. Now we want to label the values in *d*. First create an empty array *f* with the same shape (i.e. 2x3x5) as *d* using `np.empty`.


In [123]:
# your code here
f = np.empty([2,3,5])
print(f)

[[[82. 62.  0. 93. 67.]
  [ 1.  6.  5. 88. 48.]
  [14. 91. 94. 98. 87.]]

 [[20. 31. 23. 18. 55.]
  [21.  0. 87. 28. 82.]
  [ 8. 64. 69. 94. 20.]]]


#### 16. Populate the values in *f*. 

For each value in *d*, if it's larger than *d_min* but smaller than *d_mean*, assign 25 to the corresponding value in *f*. If a value in *d* is larger than *d_mean* but smaller than *d_max*, assign 75 to the corresponding value in *f*. If a value equals to *d_mean*, assign 50 to the corresponding value in *f*. Assign 0 to the corresponding value(s) in *f* for *d_min* in *d*. Assign 100 to the corresponding value(s) in *f* for *d_max* in *d*. In the end, f should have only the following values: 0, 25, 50, 75, and 100.

**Note**: you don't have to use Numpy in this question.

In [124]:
# your code here
for table in range(2):
    for row in range(3):
        for col in range(5):
            if d[table,row,col] > d_min and d[table,row,col] < d_mean:
                f[table,row,col] = 25
            elif d[table,row,col] > d_mean and d[table,row,col] < d_max:
                f[table,row,col] = 75
            elif d[table,row,col] == d_mean:
                f[table,row,col] = 50
            elif d[table,row,col] <= d_min:
                f[table,row,col] = 0
            elif d[table,row,col] >= d_max:
                f[table,row,col] = 100
print(f)
print(d)

[[[ 75.  75.   0.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]
[[[83. 63.  1. 94. 68.]
  [ 2.  7.  6. 89. 49.]
  [15. 92. 95. 99. 88.]]

 [[21. 32. 24. 19. 56.]
  [22.  1. 88. 29. 83.]
  [ 9. 65. 70. 95. 21.]]]


#### 17. Print *d* and *f*. Do you have your expected *f*?
For instance, if your *d* is:
```python
[[[1.85836099, 1.67064465, 1.62576044, 1.40243961, 1.88454931],
[1.75354326, 1.69403643, 1.36729252, 1.61415071, 1.12104981],
[1.72201435, 1.1862918 , 1.87078449, 1.7726778 , 1.88180042]],
[[1.44747908, 1.31673383, 1.02000951, 1.52218947, 1.97066381],
[1.79129243, 1.74983003, 1.96028037, 1.85166831, 1.65450881],
[1.18068344, 1.9587381 , 1.00656599, 1.93402165, 1.73514584]]]
```
Your *f* should be:
```python
[[[ 75.,  75.,  75.,  25.,  75.],
[ 75.,  75.,  25.,  25.,  25.],
[ 75.,  25.,  75.,  75.,  75.]],
[[ 25.,  25.,  25.,  25., 100.],
[ 75.,  75.,  75.,  75.,  75.],
[ 25.,  75.,   0.,  75.,  75.]]]
```

In [125]:
# your code here
print(f)
print(d)

[[[ 75.  75.   0.  75.  75.]
  [ 25.  25.  25.  75.  25.]
  [ 25.  75.  75. 100.  75.]]

 [[ 25.  25.  25.  25.  75.]
  [ 25.   0.  75.  25.  75.]
  [ 25.  75.  75.  75.  25.]]]
[[[83. 63.  1. 94. 68.]
  [ 2.  7.  6. 89. 49.]
  [15. 92. 95. 99. 88.]]

 [[21. 32. 24. 19. 56.]
  [22.  1. 88. 29. 83.]
  [ 9. 65. 70. 95. 21.]]]


#### 18. Bonus question: instead of using numbers (i.e. 0, 25, 50, 75, and 100), use string values  ("A", "B", "C", "D", and "E") to label the array elements. For the example above, the expected result is:

```python
[[[ 'D',  'D',  'D',  'B',  'D'],
[ 'D',  'D',  'B',  'B',  'B'],
[ 'D',  'B',  'D',  'D',  'D']],
[[ 'B',  'B',  'B',  'B',  'E'],
[ 'D',  'D',  'D',  'D',  'D'],
[ 'B',  'D',   'A',  'D', 'D']]]
```
**Note**: you don't have to use Numpy in this question.

In [126]:
# your code here
f = np.empty([2,3,5], dtype=str)
for table in range(2):
    for row in range(3):
        for col in range(5):
            if d[table,row,col] > d_min and d[table,row,col] < d_mean:
                f[table,row,col] = 'B'
            elif d[table,row,col] > d_mean and d[table,row,col] < d_max:
                f[table,row,col] = 'D'
            elif d[table,row,col] == d_mean:
                f[table,row,col] = 'C'
            elif d[table,row,col] <= d_min:
                f[table,row,col] = 'A'
            elif d[table,row,col] >= d_max:
                f[table,row,col] = 'E'
print(f)

[[['D' 'D' 'A' 'D' 'D']
  ['B' 'B' 'B' 'D' 'B']
  ['B' 'D' 'D' 'E' 'D']]

 [['B' 'B' 'B' 'B' 'D']
  ['B' 'A' 'D' 'B' 'D']
  ['B' 'D' 'D' 'D' 'B']]]
